### ISSUE TITLE
Task List Checking

### ISSUE THREAD

**Issue by ainigo-metcalfe** [ainigo-metcalfe/markdown-portfolio#2]
- [ ] will this work
- [ ] adding this too
how do i nest a table
- [x] will that check it?

**Comment by ainigo-metcalfe** [comment]
adding a comment
- [x] math for the day
- [ ] social studies sucks
- [ ] i am sick of my quarantine food
